version: "3.0"
services: 
  web:
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://10.250.15.2:5000"
    image: hello-brunch
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "80:80"
