version: "3.0"
services: 
  web:
    logging:
      driver: fluentd
      options:
        fluentd-address: "10.250.15.2:24224"
    image: hello-brunch
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "80:80"
